color 07
cd hdl_hdd\
IF NOT EXIST APPS\ MD APPS
IF NOT EXIST ART\  MD ART
IF NOT EXIST CFG\  MD CFG
IF NOT EXIST CHT\  MD CHT
IF NOT EXIST POPS\ MD POPS
IF NOT EXIST THM\  MD THM
IF NOT EXIST VMC\  MD VMC
cd ..
cls
CALL "hdl_hdd\.PFS-Batch-Kit-Manager.bat"
