@echo off

set LANGUAGE=Espanol


echo %LOADING% %LANGUAGE%

set LOADING=Cargando
set CONFIG_FILE=Archivo de configuracion

set YES=Si
set NO=No
set TCF=convertir apps a formato title.cfg Antes de Instalar. (se agregarán automaticamente al OPL)
set MAKE_VMC_BEFORE=Crear una VMC antes.
set ADMIN_PRIV=Obteniendo permisos de administrador...
set BASIC_CHOICE="Seleccionar Opcion:"

set Transfer=Transferir
set Applications=Aplicaciones:
set Configs=Configuraciones:
set Artwork=Caratula:
set Cheats=Cheats:
set Themes=Temas:

set INSTALLING=Instalando


set EST_FILE_SIZE=Estimando Tamano:
set Files=Archivos:
set Size=Tamano:
set IS_EMPTY=Esta vacio...
set CFG_EMPTY=No hay archivos .CFG dentro...
set CHT_EMPTY=No hay archivos .CHT dentro...
set VMC_EMPTY=No hay archivos .BIN dentro...

set VMC_SIZE_ASK=Elegir tamano
set VMC_NAME_ASK=Escribir nombre VMC sin extension


set SEARCHING_OPLPART=Detectando Particion
set DETECTED_OPLPART=Particion Detectada
set MISSING_OPLPART=Particion NO Detectada

set FORMAT_OPLPART=asegurece de que la particion exista y esté en formato PFS

set BAT_DEPS=Checkeando Dependencias...
set DEPS_MISSING=Faltante
set DEPS_FOUND=Detectado

set HDD_SCAN=Buscando HDDs en formato PS2:
set HDD_NOT_FOUND1=No se encuentra HDD en formato PS2 (PFS)
set HDD_NOT_FOUND2=Asegurese de que el HDD este conectado y formateado apropiadamente


set COMPLETED=Completado...
set CREAT_LOG=Creando Log
