name: Release HDL Batch Installer
on:
  workflow_dispatch:
  push:
#    paths:
#      - '.github/workflows/repack-and-release.yml'

  schedule:
   - cron: "0 15 * * 5"
jobs:

  Repack_and_Release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [English]
    steps:

    - name: checkout code for release
      uses: actions/checkout@v1
      
      
      
    - name: Update Widescreen Hacks Package
      run: |
        cp README.md HDD_PFS_Batch_Kit_Manager/README.MD
        cd HDD_PFS_Batch_Kit_Manager
        cd hdl_hdd
        cd BAT
        rm -f WIDE.ZIP
        wget https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases/download/Latest/widescreen_hacks.zip -O $PWD/WIDE.ZIP
    - name: Zip Folder
      run: |
        SCH=${GITHUB_SHA::7}
        PKG=${{ matrix.package }}
        cd HDD_PFS_Batch_Kit_Manager
        cd hdl_hdd
        cd BAT
        echo commit $SCH>commit.sys
        echo `date`>>commit.sys
        cd ..
        cd ..
        cd ..
        DATEE=`date '+[%Y-%m-%d]'`
        mv HDD_PFS_Batch_Kit_Manager HDD_PFS_Batch_Kit_Manager-$PKG-$DATEE
        zip -r HDD_PFS_Batch_Kit_Manager\[$SCH\] HDD_PFS_Batch_Kit_Manager-$PKG-*/*
        ls -R
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name:  ${{ matrix.package }}
        path: |
             HDD_PFS_Batch_Kit_Manager*.zip
    - name: Create release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ matrix.package }}
        title:  " HDD Art Batcher ${{ matrix.package }}"
        files: |
                HDD_PFS_Batch_Kit_Manager*.zip
